# @name login
POST {{HostAddress}}/account/login?useCookies=true&useSessionCookies=true
Content-Type: application/json
Accept: application/json
{
  "email": "user2@test.com",
  "password": "String!1"
}

###

@cookie = {{login.response.headers.Set-Cookie}}
@lastId = 409
@lastValue = 2025-09-23T09:23:18.415Z
@orderBy = dateTime
@orderDirection = 1
@isPrevious = false
@pageSize = 10

GET {{HostAddress}}/coffees?orderBy={{orderBy}}&orderDirection={{orderDirection}}&isPrevious={{isPrevious}}&pageSize={{pageSize}}&lastId={{lastID}}&lastValue={{lastValue}}
Accept: application/json
Cookie: session={{cookie}}
