# @name login
POST {{HostAddress}}/account/login?useCookies=true&useSessionCookies=true
Content-Type: application/json
Accept: application/json
{
  "email": "user5@test.com",
  "password": "String!1"
}

###

@cookie = {{login.response.headers.Set-Cookie}}

POST {{HostAddress}}/account/logout
Content-Type: application/json
Accept: application/json
Cookie: session={{cookie}}
{}